define.nextId("postal");
(function(d,l){"function"==typeof define&&define.amd?define(["lodash"],function(p){return l(p,d)}):"object"==typeof module&&module.exports?module.exports=l(require("lodash"),this):d.postal=l(d._,d)})(this,function(d,l,p){function z(a,c,b){return function(f,e,d){f===a&&d.splice(e,1);0===d.length&&delete b[c]}}function w(a,c,b,f,d){var e=d&&d.headers||{};return function(d){var k;g.resolver.compare(d.topic,a,e)&&(e.resolverNoCache||(k=c[b]=c[b]||[],k.push(d)),d.cacheKeys.push(b),f&&f(d))}}function x(a,
c){return{channel:g.SYSTEM_CHANNEL,topic:"subscription."+a,data:{event:"subscription."+a,channel:c.channel,topic:c.topic}}}function A(a,c){return"function"==typeof a?a:a?function(b){var f=0,e=0;return d.each(a,function(d,h){f+=1;("topic"===h&&c.compare(b.topic,a.topic,{resolverNoCache:!0})||"context"===h&&a.context===b._context||b[h]===a[h])&&(e+=1)}),f===e}:function(){return!0}}var B=l&&l.postal,y=l&&l._;y&&y!==d&&(d=d.noConflict());var n={configuration:d.extend({},{DEFAULT_CHANNEL:"/",SYSTEM_CHANNEL:"postal",
enableSystemMessages:!0,cacheKeyDelimiter:"|",autoCompactResolver:!1})},g=n.configuration,q=function(a,c){this.bus=c;this.channel=a||g.DEFAULT_CHANNEL};q.prototype.subscribe=function(){return this.bus.subscribe({channel:this.channel,topic:1===arguments.length?arguments[0].topic:arguments[0],callback:1===arguments.length?arguments[0].callback:arguments[1]})};q.prototype.publish=function(a,c,b){var f,d={};if("string"==typeof a?(d.topic=a,d.data=c,f=b):(d=a,f=c),"object"!=typeof d)throw Error("The first argument to ChannelDefinition.publish should be either an envelope object or a string topic.");
d.channel=this.channel;this.bus.publish(d,f)};var u=function(a,c,b){if(3!==arguments.length)throw Error("You must provide a channel, topic and callback when creating a SubscriptionDefinition instance.");if(0===c.length)throw Error("Topics cannot be empty");this.channel=a;this.topic=c;this.callback=b;this.pipeline=[];this.cacheKeys=[];this._context=p},C=function(){var a;return function(c){var b=!1;return"string"==typeof c?(b=c===a,a=c):(b=d.isEqual(c,a),a=d.extend({},c)),!b}},D=function(){var a=[];
return function(c){var b=!d.some(a,function(a){return d.isEqual(c,a)});return b&&a.push(c),b}};u.prototype={"catch":function(a){var c=this.callback;return this.callback=function(){try{c.apply(this,arguments)}catch(b){a(b,arguments[0])}},this},defer:function(){return this.delay(0)},disposeAfter:function(a){if("number"!=typeof a||0>=a)throw Error("The value provided to disposeAfter (maxCalls) must be a number greater than zero.");var c=d.after(a,this.unsubscribe.bind(this));return this.pipeline.push(function(a,
d,e){e(a,d);c()}),this},distinct:function(){return this.constraint(new D)},distinctUntilChanged:function(){return this.constraint(new C)},invokeSubscriber:function(a,c){if(!this.inactive){var b=this,d=b.pipeline,e=d.length,k=b._context,h=-1,m=!1;e?(d=d.concat([b.callback]),function E(a,c){h+=1;e>h?d[h].call(k,a,c,E):(b.callback.call(k,a,c),m=!0)}(a,c,0)):(b.callback.call(k,a,c),m=!0);return m}},logError:function(){if(console)this["catch"](console.warn?console.warn:console.log);return this},once:function(){return this.disposeAfter(1)},
subscribe:function(a){return this.callback=a,this},unsubscribe:function(){this.inactive||n.unsubscribe(this)},constraint:function(a){if("function"!=typeof a)throw Error("Predicate constraint must be a function");return this.pipeline.push(function(c,b,d){a.call(this,c,b)&&d(c,b)}),this},constraints:function(a){var c=this;return d.each(a,function(a){c.constraint(a)}),c},context:function(a){return this._context=a,this},debounce:function(a,c){if("number"!=typeof a)throw Error("Milliseconds must be a number");
var b={};return 1==!!c&&(b.leading=!0,b.trailing=!1),this.pipeline.push(d.debounce(function(a,b,c){c(a,b)},a,b)),this},delay:function(a){if("number"!=typeof a)throw Error("Milliseconds must be a number");return this.pipeline.push(function(c,b,d){setTimeout(function(){d(c,b)},a)}),this},throttle:function(a){if("number"!=typeof a)throw Error("Milliseconds must be a number");return this.pipeline.push(d.throttle(function(a,b,d){d(a,b)},a)),this}};var r=(g.resolver={cache:{},regex:{},enableCache:!0,compare:function(a,
c,b){var f,e,k,h=c+g.cacheKeyDelimiter+a,m=this.cache[h];b=b||{};b=this.enableCache&&!b.resolverNoCache;return!0===m?m:-1===a.indexOf("#")&&-1===a.indexOf("*")?(m=c===a,b&&(this.cache[h]=m),m):((e=this.regex[a])||(f="^"+d.map(a.split("."),function(a){var b="";return k&&(b="#"!==k?"\\.\\b":"\\b"),b+="#"===a?"[\\s\\S]*":"*"===a?"[^.]+":a,k=a,b}).join("")+"$",e=this.regex[a]=new RegExp(f)),m=e.test(c),b&&(this.cache[h]=m),m)},reset:function(){this.cache={};this.regex={}},purge:function(a){var c=this,
b=g.cacheKeyDelimiter,f=function(d,f){var e=f.split(b);d=e[0];e=e[1];"undefined"!=typeof a.topic&&a.topic!==d||"undefined"!=typeof a.binding&&a.binding!==e||delete c.cache[f]},e=function(a,d){a=d.split(b);0===n.getSubscribersFor({topic:a[0]}).length&&delete c.cache[d]};"undefined"==typeof a?this.reset():d.each(this.cache,!0===a.compact?e:f)}},0),v=[],t=0,F=x.bind(p,"created"),G=x.bind(p,"removed");if(d.extend(n,{cache:{},subscriptions:{},wireTaps:[],ChannelDefinition:q,SubscriptionDefinition:u,channel:function(a){return new q(a,
this)},addWireTap:function(a){var c=this;return c.wireTaps.push(a),function(){var b=c.wireTaps.indexOf(a);-1!==b&&c.wireTaps.splice(b,1)}},noConflict:function(){if("undefined"==typeof window||"undefined"!=typeof window&&"function"==typeof define&&define.amd)throw Error("noConflict can only be used in browser clients which aren't using AMD modules");return l.postal=B,this},getSubscribersFor:function(a){var c=[];return d.each(this.subscriptions,function(b){d.each(b,function(b){c=c.concat(d.filter(b,
A(a,g.resolver)))})}),c},publish:function(a,c){++r;var b=a.channel=a.channel||g.DEFAULT_CHANNEL,f=a.topic;a.timeStamp=new Date;this.wireTaps.length&&d.each(this.wireTaps,function(b){b(a.data,a,r)});var e=b+g.cacheKeyDelimiter+f,k=this.cache[e],h=0,m=0;if(k)d.each(k,function(b){b.invokeSubscriber(a.data,a)?m++:h++});else{var l=w(f,this.cache,e,function(b){b.invokeSubscriber(a.data,a)?m++:h++},a);d.each(this.subscriptions[b],function(a){d.each(a,l)})}if(0===--r)for(;v.length;)n.unsubscribe(v.shift());
c&&c({activated:m,skipped:h})},reset:function(){this.unsubscribeFor();g.resolver.reset();this.subscriptions={};this.cache={}},subscribe:function(a){var c=this.subscriptions,b=new u(a.channel||g.DEFAULT_CHANNEL,a.topic,a.callback);a=c[b.channel];var f=b.channel.length;a||(a=c[b.channel]={});(a=c[b.channel][b.topic])||(a=c[b.channel][b.topic]=[]);a.push(b);var e=this.cache;return d.each(d.keys(e),function(a){a.substr(0,f)===b.channel&&w(a.split(g.cacheKeyDelimiter)[1],e,a)(b)}),g.enableSystemMessages&&
this.publish(F(b)),b},unsubscribe:function(){for(var a,c,b,f,e=arguments.length,k=0;e>k;k++){if(a=arguments[k],a.inactive=!0,r)return void v.push(a);if(c=this.subscriptions[a.channel],b=c&&c[a.topic]){var h=b.length;for(f=0;h>f;){if(b[f]===a){b.splice(f,1);break}f+=1}if(0===b.length&&(delete c[a.topic],d.keys(c).length||delete this.subscriptions[a.channel]),a.cacheKeys&&a.cacheKeys.length)for(;b=a.cacheKeys.pop();)d.each(this.cache[b],z(a,b,this.cache));"function"==typeof g.resolver.purge&&(b=!0===
g.autoCompactResolver?0:"number"==typeof g.autoCompactResolver?g.autoCompactResolver-1:!1,0<=b&&t===b?(g.resolver.purge({compact:!0}),t=0):0<=b&&b>t&&(t+=1))}g.enableSystemMessages&&this.publish(G(a))}},unsubscribeFor:function(a){var c=[];this.subscriptions&&(c=this.getSubscribersFor(a),this.unsubscribe.apply(this,c))}}),l&&Object.prototype.hasOwnProperty.call(l,"__postalReady__")&&d.isArray(l.__postalReady__))for(;l.__postalReady__.length;)l.__postalReady__.shift().onReady(n);return n});